name: Publish Plugins

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Scrubbler

    steps:
      - name: Checkout Scrubbler-2
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Scrubbler.sln

      - name: Build plugins
        run: |
          mkdir -p artifacts/plugins
          # build every .csproj under Plugins (recursive)
          for proj in $(find Plugins -name '*.csproj'); do
            echo "Building $proj"
            dotnet build "$proj" -c Release -o artifacts/plugins
          done

      - name: Generate plugins.json
        run: dotnet run --project PluginMetadataGenerator artifacts/plugins artifacts/plugins.json https://raw.githubusercontent.com/SHOEGAZEssb/Scrubbler-Plugins/main

      - name: Checkout Scrubbler-Plugins
        uses: actions/checkout@v4
        with:
          repository: SHOEGAZEssb/Scrubbler-Plugins
          token: ${{ secrets.PLUGIN_REPO_TOKEN }}   # PAT only used for auth
          path: out

      - name: Sync plugins + manifest
        run: |
          mkdir -p out/plugins
          cp artifacts/plugins/*.dll out/plugins/
          cp artifacts/plugins.json out/

      - name: Commit and push
        working-directory: out
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update plugins from $GITHUB_SHA" || echo "No changes to commit"
          git push